import './global.css'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
export const metadata = {
  title: 'COOL POS',
  description: 'Generated by create-nx-workspace',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
